
import './AiZoo20260401.css';
import eczooMainLogoUrl from 'url:../../site/static/icons/eczoo-main-logo-contrast.svg';


function animateAiZoo20260401()
{
    let today = new Date();
    if (today.getDate() != 1 || today.getMonth() != 3) { // April is 3 since Jan is 0
        //return; // not 4/1
    }

    let bannerElement = document.createElement('div');
    bannerElement.classList.add('AiZoo20260401Banner');
    bannerElement.innerHTML = `
<div class="AiZoo20260401-BannerContent">
<b>Important Error Correction Zoo Update: A new start with AI!</b>
<a href="" class="AiZoo20260401-Banner-LearnMoreLink">Learn more...</a>
</div>
`;

    let msgElement = document.createElement('div');
    msgElement.classList.add('AiZoo20260401MsgArticleContainer');
    msgElement.innerHTML = `
<div class="AiZoo20260401-MsgArticleWrap">
<button class="AiZoo20260401-CloseBtn AiZoo20260401-CloseClickable" aria-label="Close">&times;</button>
<div class="AiZoo20260401-MsgArticleContent">
<div class="AiZoo20260401-MsgArticleContent-Title-Logo">
<div class="AiZoo20260401-MsgArticleContent-Title">
The Error Correction Zoo with the power of <span class="AiZoo20260401-wow-ai">AI</span>
</div>
<!--<img src="${eczooMainLogoUrl}">-->
</div>
<p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p><p>Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...
Lorem ipsum ... ... ...</p>
<a href="" class="AiZoo20260401-CloseClickable">Close</a>
</div>
</div>
`;

    msgElement.querySelector('.AiZoo20260401-CloseClickable').addEventListener('click', (e) => {
        msgElement.classList.remove('AiZoo20260401MsgArticleContainer-shown');
        e.preventDefault();
        return false;
    });

    let aEl = bannerElement.querySelector('a.AiZoo20260401-Banner-LearnMoreLink');
    aEl.addEventListener('click', (e) => {
        console.log('Showing full AI announcement message...');
        msgElement.classList.add('AiZoo20260401MsgArticleContainer-shown');
        e.preventDefault();
        return false;
    });

    document.body.appendChild(bannerElement);
    document.body.appendChild(msgElement);
}

window.addEventListener('load', function() {
    setTimeout(animateAiZoo20260401, 800);
});